package com.agenda.model;
// Generated 24/06/2019 16:42:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nome;
     private String login;
     private String senha;
     private Set<Contato> contatos = new HashSet<Contato>(0);

    public Usuario() {
    }

	
    public Usuario(String nome, String login, String senha) {
        this.nome = nome;
        this.login = login;
        this.senha = senha;
    }
    public Usuario(String nome, String login, String senha, Set<Contato> contatos) {
       this.nome = nome;
       this.login = login;
       this.senha = senha;
       this.contatos = contatos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set<Contato> getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set<Contato> contatos) {
        this.contatos = contatos;
    }




}


